version: 2
builds:
  - id: vigenere
    binary: vigenere
    main: ./cmd/vigenere/main.go
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  github:
    owner: simonmittag
    name: vigenerecipher

scoops:
  - name: vigenere
    repository:
      owner: simonmittag
      name: scoop-cli
    commit_author:
      name: simonmittag
      email: simonmittag@gmail.com
    description: A simple Vigenere cipher CLI tool.
    homepage: https://github.com/simonmittag/vigenerecipher
    license: Apache

universal_binaries:
  - id: vigenere
    replace: true
    name_template: "vigenere"

checksum:
  name_template: 'checksums.txt'

brews:
  - name: vigenere
    homepage: https://github.com/simonmittag/vigenerecipher
    repository:
      owner: simonmittag
      name: homebrew-cli
    commit_author:
      name: simonmittag
      email: simonmittag@gmail.com
